# Generated by Django 6.0.3 on 2026-04-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_videojobassert_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojobevent',
            name='event_type',
            field=models.CharField(choices=[('JOB_CREATED', 'Job作成'), ('WORKFLOW_STARTED', 'Workflow開始'), ('STEP_UPDATED', 'ステップ更新'), ('AI_REQUEST_SENT', 'AIリクエスト送信'), ('AI_RENDER_COMPLETED', 'AI生成完了'), ('YOUTUBE_UPLOAD_STARTED', 'YouTubeアップロード開始'), ('YOUTUBE_UPLOAD_COMPLETED', 'YouTubeアップロード完了'), ('JOB_COMPLETED', 'Job完了'), ('JOB_FAILED', 'Job失敗'), ('JOB_CANCELLED', 'Jobキャンセル')], db_index=True, max_length=40),
        ),
    ]
