# Generated by Django 6.0.3 on 2026-04-08 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_videojobevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(help_text='media/generated_videos/ 以下のパス', max_length=500, upload_to='generated_videos/')),
                ('original_url', models.URLField(blank=True, help_text='AI プロバイダーが返した元の動画 URL', max_length=1000)),
                ('generation_id', models.CharField(blank=True, db_index=True, help_text='AI プロバイダー側の生成ジョブ ID', max_length=255)),
                ('mime_type', models.CharField(default='video/mp4', max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, help_text='動画の長さ（秒）', null=True)),
                ('resolution', models.CharField(blank=True, help_text='例: 1920x1080', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'generated_videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='videojob',
            name='generated_video',
            field=models.OneToOneField(blank=True, help_text='AI が生成した完成動画（media/generated_videos/ に保存）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_job', to='jobs.generatedvideo'),
        ),
    ]
