# Generated by Django 6.0.3 on 2026-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_ai', '0005_videoaiprovidervalidationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaiprovidervalidationconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
