# Generated by Django 6.0.3 on 2026-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aivideo_component', '0004_add_description_to_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedaudio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='description',
        ),
    ]
