"""
VideoPipelineWorkflow を Temporal Client から起動するスクリプト。

使い方:
    python -m temporal.run_pipeline

    # 引数でジョブIDを指定する場合（任意）
    JOB_ID=my-job-001 python -m temporal.run_pipeline

NOTE:
  - このスクリプトは開発・動作確認用のエントリポイント
  - 本番では Django View / Management Command / API エンドポイントから
    get_temporal_client() を使って同様に start_workflow を呼ぶ
  - worker_pipeline.py を先に起動しておくこと
"""
import asyncio
import logging
import os
import uuid

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django  # noqa: E402

django.setup()

from django.conf import settings  # noqa: E402

from temporal.client import get_temporal_client  # noqa: E402
from temporal.pipeline_types import PipelineInput  # noqa: E402
from temporal.workflows.pipeline.video_pipeline_workflow import VideoPipelineWorkflow  # noqa: E402

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def start_pipeline() -> None:
    """
    VideoPipelineWorkflow を開始する。

    TODO: 本実装では Django モデルから job_id・user_id などを取得して渡す。
    """
    job_id = os.environ.get("JOB_ID", f"job-{uuid.uuid4().hex[:8]}")
    request_id = f"req-{uuid.uuid4().hex}"

    # ── ダミー入力データ ────────────────────────────────────────
    # TODO: 本実装では Django の VideoJob モデル等から取得する
    pipeline_input = PipelineInput(
        job_id=job_id,
        request_id=request_id,
        user_id=1,
        video_ai_config_id=1,
        prompt_id=1,
        image_ids=[1, 2, 3],
        audio_ids=[10],
        oauth_record_id=1,
        youtube_channel_id="UC_your_channel_id",
        publish_mode="private",
        thumbnail_url="",
        title=f"Test Video [{job_id}]",
        description="This is a test video generated by VideoPipelineWorkflow.",
        tags=["test", "ai", "video"],
    )

    client = await get_temporal_client()

    logger.info("Starting VideoPipelineWorkflow  job_id=%s", job_id)
    handle = await client.start_workflow(
        VideoPipelineWorkflow.run,
        pipeline_input,
        id=job_id,                              # Workflow ID（冪等キーとして使う）
        task_queue=settings.TEMPORAL_TASK_QUEUE,
    )

    logger.info("Workflow started  workflow_id=%s  run_id=%s", handle.id, handle.first_execution_run_id)
    logger.info("Waiting for result...")

    result = await handle.result()

    logger.info(
        "Pipeline completed!\n"
        "  job_id           : %s\n"
        "  youtube_video_id : %s\n"
        "  youtube_video_url: %s",
        result.job_id,
        result.youtube_video_id,
        result.youtube_video_url,
    )


if __name__ == "__main__":
    asyncio.run(start_pipeline())
